name: Push to Another Repo

on:
  push:
    branches:
      - main  # trigger on pushes to main

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "Tayyab008"
          git config user.email "fa22-bee-043@cuilahore.edu.pk"

      - name: Push to target repo
        run: |
          # Add the target repo as a remote
          git remote add target https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Teayab008/testing_githubaction
          
          # Push the main branch
          git push target main
