name: Docker Image CI

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]

jobs:
build:

runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Java
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: '8'

  - name: Build JAR with Maven
    run: mvn clean package

  - name: Build Docker image
    run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
```
